### ISSUE TITLE
Caeser example failing for JavaScript backend because of Math.Pow

### ISSUE THREAD

**Issue by joelmccracken** [koka-lang/koka#165]
```
node ./out/v2.1.1/js-debug/samples_basic_caesar.js                                                     ~/Inbox/idk
/Users/joel/Inbox/idk/out/v2.1.1/js-debug/std_num_double.js:43
var _splitter    = Math.Pow(2,27) + 1;      // 0x1.0000002p+27 // 134217729.0 = 2^27 + 1
                        ^

TypeError: Math.Pow is not a function
    at Object.<anonymous> (/Users/joel/Inbox/idk/out/v2.1.1/js-debug/std_num_double.js:43:25)
    at runFactory (/Users/joel/Inbox/idk/node_modules/amdefine/amdefine.js:183:30)
    at define (/Users/joel/Inbox/idk/node_modules/amdefine/amdefine.js:277:13)
    at Object.<anonymous> (/Users/joel/Inbox/idk/out/v2.1.1/js-debug/std_num_double.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at req (/Users/joel/Inbox/idk/node_modules/amdefine/amdefine.js:144:31)
```

problem appears to be here: https://github.com/koka-lang/koka/blob/756ce23b093872bdfc4107d31e1c9b647a56ce70/lib/std/num/double-inline.js#L45-L48

**Comment by anfelor** [comment]
Thanks, this is fixed on current `dev` now. It will most likely be included in a new release to be published in a few weeks
