### ISSUE TITLE
Can't execute and get "Invalid argument"

### ISSUE THREAD

**Issue by YiChiaosu** [koka-lang/koka#58]
hey, I try to build koka by executing `jake`   in windows
and get a error below:
```
check for packages: random text parsec
build: koka 0.8.0-dev (debug version)
build ok.
> out\debug\koka-0.8.0-dev.exe  --outdir=out\lib -ilib -itest/algeff -itest/lib
invalid argumentjake aborted.
Error: Process exited with error.
    at api.fail (C:\Users\hchs8\AppData\Roaming\npm\node_modules\jake\lib\api.js:336:18)
    at Exec.<anonymous> (C:\Users\hchs8\AppData\Roaming\npm\node_modules\jake\lib\utils\index.js:124:9)
(See full trace by running task with --trace)
```
I try to run koka-0.8.0-dev.exe directly, but get "Invalid argument" no matter what I input.

**Comment by dhil** [comment]
I cannot reproduce this issue. I suspect it has been fixed. If not feel free to reopen the issue.

**Comment by freddie-freeloader** [comment]
Hi!

Unfortunately, I get the same error on koka-0.9.0-dev, when running `jake`. `jake compiler` works though.

The output I get

```
jub@coruscant ~/G/koka> jake
Starting 'config'...
check for packages: text parsec
Finished 'config' after 31 ms
Starting 'compiler'...
build: koka 0.9.0-dev (debug version)
build ok.
Finished 'compiler' after 8 ms
Starting 'interactive'...
> out/debug/koka-0.9.0-dev  --outdir=out/lib -ilib -itest/algeff -itest/implicits -itest/ambients -itest/instance -itest/lib --core --checkcore 
invalid argumentjake aborted.
Error: Process exited with error.
    at api.fail (/usr/lib/node_modules/jake/lib/api.js:336:18)
    at Exec.<anonymous> (/usr/lib/node_modules/jake/lib/utils/index.js:123:9)
    at Exec.emit (events.js:198:13)
    at ChildProcess.<anonymous> (/usr/lib/node_modules/jake/lib/utils/index.js:226:16)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
```

Any ideas why this might happen? :slightly_smiling_face:

**Comment by freddie-freeloader** [comment]
I compiled Koka again with `stack` instead of `cabal` and this resolved the error for me.
